### ISSUE TITLE
Doesn't register [ok] button or fire tv stick 

### ISSUE THREAD

**Issue by manishsingh10895** [kananinirav/Indian-IPTV-App#7]
I installed the latest apk (1.3.0) through adb on my firetv stick. It installed successfully and opened the list of channels.
But pressing ok button doesn't do anything.

**Comment by kananinirav** [comment]
Let me check on that 👀

**Comment by saheelraut** [comment]
Same behavior seen on Google TV, Okay button not registering.

**Comment by kananinirav** [comment]
Fixed with https://github.com/kananinirav/Indian-IPTV-App/releases/tag/v2.0.0
