### ISSUE TITLE
IPTV (m3u) link request 

### ISSUE THREAD

**Issue by VishveshC** [kananinirav/Indian-IPTV-App#8]
Please provide with the m3u link personally if possible. Would do anything to get it 🙏

**Comment by kananinirav** [comment]
@VishveshC Already available in [Credits](https://github.com/kananinirav/Indian-IPTV-App?tab=readme-ov-file#credits) section. 

[Channel Source](https://github.com/aniketda/iptv2050)

**Comment by TecnikOfficial** [comment]
> [Channel Source](https://github.com/aniketda/iptv2050)
this source is filled with bangla channel if possible try to add punjabi or other language channels too
